### PR TITLE
[ci] Hardcode number of jobs and revise action trigger

### PR DESCRIPTION
**Pull request by jberdine**

### CODE REVIEW

**Comment by jberdine** [comment]
The compiler CI job failures are due to circleci misreporting the number of processors, this seems to fix it.

**Comment by beauby** [comment]
Interesting. It shouldn't crash/hang though.

**Comment by jberdine** [comment]
It is a memory issue. If I simulate using a docker container with 8 CPUs and 16 GB RAM, running `skargo test --jobs 36` and monitoring with `htop` shows that memory is exhausted almost instantly, and all hell breaks loose then. That is only ~450MB per process so it makes sense.

**Comment by beauby** [comment]
That makes sense. I have a branch somewhere that mitigates (some of) the memory hungriness of sktest, I'll dig it back.

**Comment by jberdine** [comment]
It can't just be sktest though. Just trying to run 36 copies of skc, each with its own clang process, in 16GB is just not going to work.

**Pull request merged**
