### PR TITLE
Purge without a buffer in the simulator

### PR DESCRIPTION
**Pull request by gregsexton**
This makes purging much more aggressive and surfaced a few issues that I fixed.

### CODE REVIEW

**Comment by gregsexton** [comment]
```
> client server single orthogonal insert each......Ran 6 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 delete on client2 diff key......Ran 840 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 delete on client2 same key......Ran 840 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 delete on client2 diff key purge server......Ran 8400 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 delete on client2 diff key purge 1......Ran 8400 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 insert on client2......Ran 840 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 delete on client2 same key purge 1......Ran 8400 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 update on client2 diff key......Ran 840 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 delete on client2 same key purge server......Ran 8400 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 update on client2 same key......Ran 840 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 update on client2 diff key purge 1......Ran 8400 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 update on client2 diff key purge server......Ran 8400 schedules, all PASSED expectation checks
> two clients single server repeat inserts on client1 purge on 1......Ran 2800 schedules, all PASSED expectation checks
> two clients single server single conflicting insert each......Ran 3360 schedules, all PASSED expectation checks
> two clients single server two conflicting inserts each......Ran 40 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 update on client2 same key purge 1......Ran 8400 schedules, all PASSED expectation checks
> two clients single server multiple inserts on client1 update on client2 same key purge server......Ran 8400 schedules, all PASSED expectation checks
> two clients single server two conflicting inserts with causality......Ran 1680 schedules, all PASSED expectation checks
> two clients single server updates......Ran 8400 schedules, all PASSED expectation checks
> two clients single server updates purge happens on1......Ran 8400 schedules, all PASSED expectation checks
> two clients single server updates purge happens on server......Ran 8400 schedules, all PASSED expectation checks
( cd sql/test/replication/ && python3 test_pk.py; )  3869.91s user 9040.40s system 600% cpu 35:48.79 total
```

**Review by jberdine — APPROVED** [review]
LGTM. The change making `skdb compact` purge right up to the current tick makes sense too.

**Comment by gregsexton** [comment]
Lots more debugging and another fix today. The soak seemed to be more flaky with this in so I held off shipping. Today I figured out why. This now passes all the simulator tests - I had to relax a couple unfortunately, but they will get fixed properly once resets are killed - and I'll kick off the soak tonight. I expect it to be solid now. Famous last words.

**Comment by gregsexton** [comment]
Rock solid soak test. It's still running in fact. Up to nearly a million rows with ~18hrs of expectation checking. Merging!

**Pull request merged**
