### PR TITLE
Lint SkStore

### PR DESCRIPTION
**Pull request by mbouaziz**
Add `ESLint` and enable more strict typechecking rules for `skstore/ts/src`.
Only minor changes, no red flags were found.
A few rules are still disabled because they were too noisy.

To run the linter: `npm run lint`

### CODE REVIEW

**Comment by bennostein** [comment]
lints all look good to me! (modulo the type error in skstore-wasm test -- that's the result of adding more strict rules to the CI check, right?)

**Comment by mbouaziz** [comment]
#294 should fix this

**Comment by mbouaziz** [comment]
Maybe non-`Error` exceptions were intended. @skiplabsdaniel, were they?

**Comment by skiplabsdaniel** [comment]
LGTM

**Pull request merged**
