### PR TITLE
[sqlparser] Allow keywords as identifiers in various places.

### LINKED ISSUE #29: Soak is broken with new parser
`make test-soak` results in the following. Doesn't support naming expressions? cc @beauby 

```
Running expectation checks for checkpoint { client: 1, latest_id: 30 }
file:///skfs/build/package/skdb/dist/sk_types.mjs:195
                let error = new SkRuntimeExit(exitCode, message?.trim());
                            ^

SkRuntimeExit [Error]: select client, value >= @latest_id as check
                                      ^
                                      |
                                       ----- ERROR
Error: line 1, character 38:
Unexpected token CHECK: expected IDENTIFIER
Internal error: select client, value >= @latest_id as check
                                      ^
                                      |
                                       ----- ERROR
Error: line 1, character 38:
Unexpected token CHECK: expected IDENTIFIER
    at Utils.main (file:///skfs/build/package/skdb/dist/sk_types.mjs:195:29)
    at SKDBSyncImpl.main [as runLocal] (file:///skfs/build/package/skdb/dist/skdb_skdb.mjs:208:33)
    at file:///skfs/build/package/skdb/dist/skdb_database.mjs:78:29
    at SKDBSyncImpl.runner (file:///skfs/build/package/skdb/dist/skdb_skdb.mjs:199:30)
    at SKDBSyncImpl.exec (file:///skfs/build/package/skdb/dist/skdb_database.mjs:76:25)
    at SKDBImpl.exec (file:///skfs/build/package/skdb/dist/skdb_database.mjs:197:46)
    at check_expectation (file:///skfs/sql/server/test/soak_client.mjs:154:30)
    at check_expectations (file:///skfs/sql/server/test/soak_client.mjs:204:3)
    at file:///skfs/sql/server/test/soak_client.mjs:356:9
    at file:///skfs/build/package/skdb/dist/skdb_skdb.mjs:238:21 {
  code: 0,
  cause: SkException [Error]: Unexpected token CHECK: expected IDENTIFIER
      at Utils.ethrow (file:///skfs/build/package/skdb/dist/sk_types.mjs:328:23)
      at LinksImpl.js_throw (file:///skfs/build/package/skdb/dist/sk_runtime.mjs:30:53)
      at toWasm.js_throw (file:///skfs/build/package/skdb/dist/sk_runtime.mjs:128:58)
      at SKIP_throw (wasm://wasm/00dc0932:wasm-function[2247]:0x34921)
      at SQLParser.Parser__errorUnexpectedToken (wasm://wasm/00dc0932:wasm-function[4707]:0xbd0a6)
      at sk.SQLParser_Parser__parseSelectResult (wasm://wasm/00dc0932:wasm-function[5409]:0xf2cf3)
      at sk.SQLParser_Parser__parseSelectResults (wasm://wasm/00dc0932:wasm-function[5407]:0xf27af)
      at sk.SQLParser_Parser__parseSelectCoreQuery (wasm://wasm/00dc0932:wasm-function[3694]:0x8035a)
      at sk.SQLParser_Parser__parseSelectCore__Closure0__call (wasm://wasm/00dc0932:wasm-function[3693]:0x802c2)
      at SQLParser.Parser__parse_one_of_keywords (wasm://wasm/00dc0932:wasm-function[4714]:0xbd644) {
    cause: SkRuntimeExit [Error]: select client, value >= @latest_id as check
                                          ^
                                          |
                                           ----- ERROR
    Error: line 1, character 38:
    Unexpected token CHECK: expected IDENTIFIER
    
        at Utils.exit [as SKIP_throw_cruntime] (file:///skfs/build/package/skdb/dist/sk_types.mjs:89:19)
        at toWasm.SKIP_throw_cruntime (file:///skfs/build/package/skdb/dist/sk_runtime.mjs:129:58)
        at SKIP_exit (wasm://wasm/00dc0932:wasm-function[4663]:0xb8480)
        at sk.skipExit.6 (wasm://wasm/00dc0932:wasm-function[3502]:0x76f58)
        at sk.SKDB_main__Closure0__call__Closure1__call (wasm://wasm/00dc0932:wasm-function[3495]:0x76a28)
        at sk.SKDB_main__Closure0__call (wasm://wasm/00dc0932:wasm-function[4116]:0x95443)
        at sk.vtry__Closure0__call.17 (wasm://wasm/00dc0932:wasm-function[3458]:0x74fcd)
        at SKIP_call0 (wasm://wasm/00dc0932:wasm-function[5777]:0x10814a)
        at Utils.call (file:///skfs/build/package/skdb/dist/sk_types.mjs:276:33)
        at Utils.etry [as SKIP_etry] (file:///skfs/build/package/skdb/dist/sk_types.mjs:293:29) {
      code: 1
    }
  }
}
```

### PR DESCRIPTION
**Pull request by beauby**
Fixes #29.

### CODE REVIEW

**Comment by gregsexton** [comment]
Thanks for making the change. Do you think we should do this? Feels like complexity we don't really need to support? I mentioned this in the issue: sqlite also doesn't like using check like this.

**Comment by gregsexton** [comment]
I'll change the tests to unblock quickly and then leave this with you to land or abandon.

**Comment by gregsexton** [comment]
fyi: https://github.com/SkipLabs/skdb/pull/18/commits/23d61a551cc68519e82310fefa4d70441b81838b

**Comment by beauby** [comment]
> Thanks for making the change. Do you think we should do this? Feels like complexity we don't really need to support? I mentioned this in the issue: sqlite also doesn't like using check like this.

My take is that we should either be strict about it everywhere (which may cause a little bit of friction as there are [quite a few keywords](https://www.sqlite.org/lang_keywords.html)), or be as flexible as possible (more or less what this PR does, as there are a few places where it would be ambiguous).

The main benefit of being strict would be that we don't have to store the input string for each keyword (in order to preserve case), but unless we're dealing with huge queries it is unlikely to make a difference.

**Comment by gregsexton** [comment]
If we don't have a good reason to choose one or other, I'd suggest:

Keep complexity down unless there's a motivating reason to introduce it.

Seems like this doesn't justify the complexity?

**Comment by jberdine** [comment]
It seems to me that it would be better to support delimited identifiers than to try to allow reserved words appear as identifiers. That approach seems to be the common one, see https://en.wikibooks.org/wiki/SQL_Dialects_Reference/Data_structure_definition/Delimited_identifiers although SQLite does apparently allow some reserved words to be used "naked" as identifiers.

**Comment by beauby** [comment]
@jberdine Agreed. Note that we do already support delimited identifiers (though I just noticed it is bugged for expressions, will send a PR).

**Comment by beauby** [comment]
@jberdine Actually I spoke too fast, it is working.

**Pull request closed without merging**
