### PR TITLE
VSCode extension for Skip basic language support

### PR DESCRIPTION
**Pull request by mbouaziz**
Mostly done by @skiplabsdaniel 

Can be easily installed with a symbolic link to it in `~/.vscode/extensions`

### CODE REVIEW

**Comment by gregsexton** [comment]
Is VSCode programmed using a json-based DSL??

**Comment by gregsexton** [comment]
Ship it when ready, of course.

**Comment by mbouaziz** [comment]
> Is VSCode programmed using a json-based DSL??

Looks like grammars are but otherwise extensions are written in JS I think

**Comment by mbouaziz** [comment]
I ended up moving this to a new repository https://github.com/SkipLabs/vscode-skip and publishing the extension to the official VSCode extension marketplace.

**Pull request merged**
